# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9caed90b7f24a8b4562457610651770d"
name = "cuvee-privee-recharge"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
